# Generated by Django 5.2.1 on 2025-05-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatars/default-avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
