# Generated by Django 5.2 on 2025-05-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('offer_date', models.DateField()),
                ('offer_expiration', models.DateField()),
                ('offer_status', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('offer_price', models.IntegerField()),
            ],
        ),
    ]
