# Generated by Django 5.2.1 on 2025-05-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.propertytype'),
            preserve_default=False,
        ),
    ]
