# Generated by Django 5.2.1 on 2025-05-16 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=20)),
                ('user_cover_image', models.CharField(blank=True, max_length=4096)),
                ('logo', models.CharField(blank=True, max_length=4096)),
                ('address', models.CharField(blank=True, max_length=4096)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('user_is_realestate', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
