# Generated by Django 5.2 on 2025-05-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('user_type', models.CharField(max_length=20)),
                ('user_cover_image', models.CharField(max_length=4096)),
                ('logo', models.CharField(max_length=4096)),
                ('address', models.CharField(max_length=4096)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('bio', models.TextField(max_length=1000)),
                ('user_is_realestate', models.BooleanField()),
            ],
        ),
    ]
